version: "3"
services: 
  web:
    environment: 
      - REDIS_URL=${REDIS_URL}
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    user: "node:node"
    ports:
      - "3500:3500"
    container_name: hi-io-container